name = "fourthwall"
main = "src/index.js"
compatibility_date = "2026-09-06"
workers_dev = true

[triggers]
crons = ["0 4 * * 1"]

[[d1_databases]]
binding = "DB"
database_name = "the-fourth-wall"
database_id = "f68bc3e1-6402-4f51-b381-8a6adb8782fc"
