const $ = selector => document.querySelector(selector);
let workspace;
const escapeHtml = value => String(value || '').replace(/[&<>"']/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[char]));
async function request(url, options = {}) { const response = await fetch(url, { headers: { 'Content-Type': 'application/json' }, ...options }); const data = response.status === 204 ? {} : await response.json(); if (!response.ok) throw new Error(data.error || 'Something went wrong.'); return data; }
function setView(name) { document.querySelectorAll('.view').forEach(view => view.classList.toggle('active', view.id === name)); document.querySelectorAll('.nav-item').forEach(button => button.classList.toggle('active', button.dataset.view === name)); $('#pageTitle').textContent = name === 'overview' ? 'Good morning.' : name === 'inquiries' ? 'Client conversations.' : 'Work in motion.'; }
function inquiryMarkup(item, short = false) { return `<article class="inquiry-row"><div><h3>${escapeHtml(item.name)} <small>· ${escapeHtml(item.company || 'Independent client')}</small></h3><p>${escapeHtml(item.service || 'General inquiry')} · ${escapeHtml(item.email)}</p>${short ? '' : `<p class="detail">${escapeHtml(item.details)}</p>`}</div>${short ? `<span class="status">${item.status}</span>` : `<select class="status-select" data-inquiry-id="${item.id}">${['New','Contacted','Qualified','Closed'].map(status => `<option ${status === item.status ? 'selected' : ''}>${status}</option>`).join('')}</select>`}</article>`; }
function projectMini(item) { return `<article class="project-mini"><strong>${escapeHtml(item.name)} <span>· ${item.progress}%</span></strong><span>${escapeHtml(item.service)} · ${escapeHtml(item.status)}</span><div class="bar"><i style="width:${item.progress}%"></i></div></article>`; }
function projectCard(item) { return `<article class="project-card"><span class="status">${escapeHtml(item.status)}</span><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.service)}</p><div class="bar"><i style="width:${item.progress}%"></i></div><footer><span>${item.progress}% complete</span><span>${item.dueDate ? `Due ${item.dueDate}` : 'No due date'}</span></footer></article>`; }
function render() { const { inquiries, projects, summary } = workspace; $('#metricNew').textContent = summary.newInquiries; $('#metricProjects').textContent = summary.activeProjects; $('#metricLeads').textContent = summary.totalInquiries; $('#leadBadge').textContent = summary.newInquiries || ''; $('#recentInquiries').innerHTML = inquiries.length ? inquiries.slice(0, 4).map(item => inquiryMarkup(item, true)).join('') : '<p class="empty">No inquiries yet. Your public contact form is connected and ready.</p>'; $('#allInquiries').innerHTML = inquiries.length ? inquiries.map(item => inquiryMarkup(item)).join('') : '<p class="empty">No inquiries yet.</p>'; $('#projectPulse').innerHTML = projects.map(projectMini).join(''); $('#allProjects').innerHTML = projects.map(projectCard).join(''); document.querySelectorAll('[data-inquiry-id]').forEach(select => select.addEventListener('change', async event => { try { await request(`/api/admin/inquiries/${event.target.dataset.inquiryId}`, { method: 'PATCH', body: JSON.stringify({ status: event.target.value }) }); await loadWorkspace(); } catch (error) { alert(error.message); } })); }
async function loadWorkspace() { workspace = await request('/api/admin/workspace'); render(); }
async function boot() { const session = await request('/api/auth/session'); if (session.user) { $('#loginView').classList.add('hidden'); $('#appView').classList.remove('hidden'); await loadWorkspace(); } }
$('#loginForm').addEventListener('submit', async event => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await request('/api/auth/login', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); await boot(); } catch (error) { $('#loginError').textContent = error.message; } });
document.querySelectorAll('.nav-item').forEach(button => button.addEventListener('click', () => setView(button.dataset.view))); document.querySelectorAll('[data-switch-view]').forEach(button => button.addEventListener('click', () => setView(button.dataset.switchView)));
$('#logoutButton').addEventListener('click', async () => { await request('/api/auth/logout', { method: 'POST' }); location.reload(); });
const dialog = $('#projectDialog'); document.querySelectorAll('[data-open-project]').forEach(button => button.addEventListener('click', () => dialog.showModal())); $('#progressInput').addEventListener('input', event => { $('#progressValue').textContent = `${event.target.value}%`; });
$('#projectForm').addEventListener('submit', async event => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await request('/api/admin/projects', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); dialog.close(); event.currentTarget.reset(); $('#progressValue').textContent = '0%'; await loadWorkspace(); setView('projects'); } catch (error) { $('#projectError').textContent = error.message; } });
boot().catch(() => {});
